Cambios Administrativos
juliocesar1235/pumm-entregable-final pull request #7
Opened 2020-10-08 01:47 UTC by ncgo

2020-10-08 15:03 UTC, juliocesar1235 commented on clases.html
> +    <link rel="stylesheet" href="styles.css">
Creo que se está haciendo referencia al mismo archivo de css. Ya estaba desde antes pero es un error

2020-10-08 15:05 UTC, juliocesar1235 commented on clases.html
> +            <a href="#" class="navbar-brand">
Este anchor te debe de llegar al index.html

2020-10-08 15:07 UTC, juliocesar1235 commented on clases.html
> +              <a href="recursos.html" class="nav-link d-inline-block" style="color: white;">Recursos</a>
Esto no es tan crucial, pero podríamos cambiar el orden de los links para la navegación. Primero las clases, luego las grabaciones, después los recursos y al final el equipo. Es una recomendación :)

2020-10-08 15:10 UTC, juliocesar1235 commented on clases.html
> +                  <a href="semana02.html"><img class="card-img" src="./libraries/assets/landing/11.png" alt="Clase 2"></a>
Quitar todos los links a archivos html que no están creados. Luego los niños se pueden asustar porque les salta el error de pagina no encontrada.

2020-10-08 15:14 UTC, juliocesar1235 commented on recursos.html
> +            </div>
Igual y aquí podemos poner un mensaje de próximamente

2020-10-08 15:16 UTC, juliocesar1235 requested changes
Fueron bastantitos cambios, te quedo super bien 💯   se ve mucho mejor el diseño y me gusto la pagina de equipo.

Te deje algunos comentarios para cambios menores 👍

2020-10-10 05:09 UTC, ncgo commented on clases.html
> +    <link rel="stylesheet" href="styles.css">
Sí, aparece doble la referencia a styles.css, ya se los quité

2020-10-11 01:51 UTC, ncgo commented on clases.html
> +                  <a href="semana02.html"><img class="card-img" src="./libraries/assets/landing/11.png" alt="Clase 2"></a>
Agregué una página de Proximamente 👍

2020-10-11 01:54 UTC, ncgo commented on recursos.html
> +            </div>
Listop

2020-10-12 03:27 UTC, juliocesar1235 approved these changes
Ya está listo Nadia! Increíble aportación 💯

2020-10-12 06:30 UTC, merged